struggling with: ---- simdrive::tests::test_sim_drive_hev stdout ---- thread 'simdrive::tests::test_sim_drive_hev' panicked at fastsim-core/src/simdrive.rs:527:19: called `Result::unwrap()` on an `Err` value: [fastsim-core/src/simdrive.rs:182] time step: 203
Caused by:
    0: [fastsim-core/src/simdrive.rs:197]
    1: [fastsim-core/src/vehicle/vehicle_model.rs:629]
    2: [fastsim-core/src/vehicle/hev.rs:122]
    3: [fastsim-core/src/vehicle/powertrain/reversible_energy_storage.rs:303]
       `self.state.pwr_disch_max` (-400 W) must be greater than or equal to zero
       [fastsim-core/src/vehicle/powertrain/reversible_energy_storage.rs:306] soc_buffer: 0.01918883490194247